#ifndef CPQ_H
#define CPQ_H

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h> /* Added for variable argument handling */
#include "error.h"
/* Expected length of the file extension (".ou" is 3 characters) */
#define LENEXT 3
extern void report_error(const char *format, ...);
extern const char* error_messeges[];
/* Extern declarations for file pointers used by cpq.c */
extern FILE* yyin;   /* Input file pointer (from the lexer/parser) */
 FILE* quad;   /* Output file pointer for quad commands */

/* Declare the parser function and error indicator.
   These should be defined in your parser module (e.g., generated by Bison). */
extern int yyparse(void);
extern int error_number;

/* Function prototype for openFile */
FILE* openFile(char* name, char* type);


#endif /* CPQ_H */
